// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKNj55FDZf4jzGLQS8kqOw6JUnnMs1YDc',
    appId: '1:468700331763:android:29ad1cba4677ccc6a24186',
    messagingSenderId: '468700331763',
    projectId: 'mobile-biometric-voting-system',
    databaseURL: 'https://mobile-biometric-voting-system-default-rtdb.firebaseio.com',
    storageBucket: 'mobile-biometric-voting-system.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDNh38YS00G44wizHacQFsDqb-KWk04cQ',
    appId: '1:468700331763:ios:c18f4a0479c64b59a24186',
    messagingSenderId: '468700331763',
    projectId: 'mobile-biometric-voting-system',
    databaseURL: 'https://mobile-biometric-voting-system-default-rtdb.firebaseio.com',
    storageBucket: 'mobile-biometric-voting-system.appspot.com',
    iosBundleId: 'com.horizons.mbvs',
  );
}
